package com.jarvis.assistant.ui

data class S(
    val appName: String, val pickTitle: String, val pickSub: String, val hwLine: String,
    val recommended: String, val slow: String, val tooBig: String, val download: String, val use: String,
    val cancel: String, val inUse: String, val delete: String, val sizeUnknown: String, val level: String,
    val licenseTitle: String, val licenseBody: String, val accept: String, val decline: String,
    val hint: String, val stIdle: String, val stListen: String, val stThink: String, val stSpeak: String,
    val stWeb: String, val greeting: String, val tapToTalk: String, val copy: String,
    val cloudChip: String, val cloudBadge: String, val webBadge: String,
    val askTitle: String, val askBody: String, val askYes: String, val askNo: String,
    val settings: String, val language: String, val humor: String, val humorLow: String, val humorHigh: String,
    val readTyped: String, val webSearch: String, val cloudMode: String, val off: String, val ask: String, val auto: String,
    val sourceOrder: String, val changeModel: String, val braveKey: String, val cloudUrl: String,
    val cloudKey: String, val cloudModel: String, val history: String, val newChat: String,
    val emptyHistory: String, val close: String, val cloudHelp: String,
    val noModel: String, val error: String, val empty: String, val micFail: String, val cloudFail: String,
    val mic: String, val send: String, val stop: String, val hardware: String,
)

val FA = S(
    appName = "جارویس", pickTitle = "انتخاب جارویس", pickSub = "گوشی‌ت رو بررسی کردم و مناسب‌ترین نسخه رو پیشنهاد میدم.",
    hwLine = "رم %s گیگ · %s · فضای خالی %s گیگ", recommended = "پیشنهادی برای گوشی شما", slow = "سرعت پایین",
    tooBig = "رم گوشی کمه", download = "دانلود", use = "استفاده", cancel = "لغو", inUse = "در حال استفاده",
    delete = "حذف", sizeUnknown = "حجم نامشخص", level = "سطح",
    licenseTitle = "شرایط استفاده از Gemma",
    licenseBody = "مدل‌های Gemma تحت شرایط استفاده گوگل ارائه میشن (ai.google.dev/gemma/terms). با ادامه، قبول میکنی که این شرایط رو خوندی و میپذیری.",
    accept = "قبول دارم", decline = "نه",
    hint = "پیام بده…", stIdle = "آماده", stListen = "گوش می‌دم…", stThink = "دارم فکر می‌کنم…", stSpeak = "دارم جواب می‌دم",
    stWeb = "دارم تو اینترنت می‌گردم…", greeting = "سلام، من جارویسم. چه کمکی می‌خوای؟",
    tapToTalk = "برای صحبت، روی من بزن", copy = "کپی", cloudChip = "پاسخ دقیق‌تر (ابری)", cloudBadge = "ابری", webBadge = "با جستجوی وب",
    askTitle = "این سوال سنگینه", askBody = "میخوای به یک هوش مصنوعی رایگان ابری بفرستمش؟ متن سوالت از گوشی خارج میشه.",
    askYes = "بفرست به ابر", askNo = "همین‌جا جواب بده",
    settings = "تنظیمات", language = "زبان", humor = "میزان شوخ‌طبعی", humorLow = "جدی", humorHigh = "شوخ",
    readTyped = "جواب‌های تایپی هم بلند خونده بشن", webSearch = "جستجوی اینترنت برای سوال‌های تازه / مقایسه",
    cloudMode = "هوش مصنوعی ابری برای سوال‌های سخت", off = "خاموش", ask = "اول بپرس", auto = "خودکار",
    sourceOrder = "اول از Ollama دانلود کن (پیش‌فرض: Hugging Face)", changeModel = "تغییر مدل",
    braveKey = "کلید Brave Search (اختیاری)", cloudUrl = "آدرس API سازگار با OpenAI (اختیاری)",
    cloudKey = "کلید API (اختیاری)", cloudModel = "نام مدل (اختیاری)", history = "تاریخچه", newChat = "گفتگوی جدید",
    emptyHistory = "هنوز گفتگویی نداری.", close = "بستن",
    cloudHelp = "بدون آدرس، از سرویس‌های رایگان بدون ثبت‌نام استفاده میشه. اگه کار نکرد، آدرس و کلید Gemini یا OpenRouter خودت رو بذار.",
    noModel = "هنوز مدلی نصب نشده.", error = "مشکلی پیش اومد: ", empty = "جوابی نگرفتم، دوباره بپرس.",
    micFail = "صدات رو نشنیدم.", cloudFail = "اتصال به هوش مصنوعی ابری ناموفق بود.",
    mic = "میکروفون", send = "ارسال", stop = "توقف", hardware = "سخت‌افزار",
)

val EN = S(
    appName = "Jarvis", pickTitle = "Choose your Jarvis", pickSub = "I checked your phone and picked the best fit.",
    hwLine = "RAM %s GB · %s · %s GB free", recommended = "Recommended for your phone", slow = "Slow",
    tooBig = "Not enough RAM", download = "Download", use = "Use", cancel = "Cancel", inUse = "In use",
    delete = "Delete", sizeUnknown = "Size unknown", level = "Level",
    licenseTitle = "Gemma terms of use",
    licenseBody = "Gemma models are provided under Google's terms (ai.google.dev/gemma/terms). By continuing you confirm you've read and accept them.",
    accept = "I accept", decline = "No",
    hint = "Message…", stIdle = "Ready", stListen = "Listening…", stThink = "Thinking…", stSpeak = "Answering",
    stWeb = "Searching the web…", greeting = "Hi, I'm Jarvis. How can I help?",
    tapToTalk = "Tap me to talk", copy = "Copy", cloudChip = "Better answer (cloud)", cloudBadge = "Cloud", webBadge = "Used web search",
    askTitle = "That's a hard one", askBody = "Send it to a free cloud AI? Your question text will leave the phone.",
    askYes = "Send to cloud", askNo = "Answer here",
    settings = "Settings", language = "Language", humor = "Humor level", humorLow = "Serious", humorHigh = "Witty",
    readTyped = "Read typed answers aloud too", webSearch = "Web search for fresh facts / comparisons",
    cloudMode = "Cloud AI for hard questions", off = "Off", ask = "Ask first", auto = "Automatic",
    sourceOrder = "Download from Ollama first (default: Hugging Face)", changeModel = "Change model",
    braveKey = "Brave Search key (optional)", cloudUrl = "OpenAI-compatible API URL (optional)",
    cloudKey = "API key (optional)", cloudModel = "Model name (optional)", history = "History", newChat = "New chat",
    emptyHistory = "No chats yet.", close = "Close",
    cloudHelp = "With no URL, free no-signup services are used. If they stop working, add your own Gemini or OpenRouter URL and key.",
    noModel = "No model installed yet.", error = "Something went wrong: ", empty = "I got no answer, please ask again.",
    micFail = "I didn't catch that.", cloudFail = "Couldn't reach the cloud AI.",
    mic = "Mic", send = "Send", stop = "Stop", hardware = "Hardware",
)

fun strings(lang: String) = if (lang == "fa") FA else EN
